const fs = require("fs");
const path = require("path");
const iniparser = require("ini");

const config = iniparser.parse(
    fs.readFileSync(path.join(__dirname, "..", "Config", "config.ini")).toString()
);

const defaultGamePath = path.join(__dirname, "..", "CloudStorage", "DefaultGame.ini");

const bloomText = `
# Straight Bloom
[AssetHotfix]
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Scope_Athena_C_Ore_T03;Spread;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Scope_Athena_UC_Ore_T03;Spread;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Scope_Athena_R_Ore_T03;Spread;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Scope_Athena_SR_Ore_T03;Spread;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Scope_Athena_VR_Ore_T03;Spread;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Heavy_Athena_UR_Ore_T03;Spread;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Heavy_Athena_SR_Ore_T03;Spread;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Heavy_Athena_VR_Ore_T03;Spread;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Heavy_Athena_R_Ore_T03;Spread;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Scope_Suppressed_Athena_SR_Ore_T03;Spread;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Scope_Suppressed_Athena_VR_Ore_T03;Spread;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Scope_Suppressed_Athena_R_Ore_T03;Spread;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Standard_Scope_Athena_SR_Ore_T03;Spread;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Standard_Scope_Athena_VR_Ore_T03;Spread;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Standard_Scope_Athena_HighTier_SR_Ore_T03;Spread;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Standard_Scope_Athena_HighTier_VR_Ore_T03;Spread;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Weather_Athena_SR_Ore_T03;Spread;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Weather_Athena_VR_Ore_T03;Spread;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Hunter_Athena_C_Ore_T03;Spread;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Hunter_Athena_UC_Ore_T03;Spread;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Hunter_Athena_R_Ore_T03;Spread;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Hunter_Athena_VR_Ore_T03;Spread;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Hunter_Athena_SR_Ore_T03;Spread;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;WaffleTruck_Sniper_DragonBreath;Spread;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Weather_Athena_SR_Ore_T03;Spread;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Heavy_Boom_Athena_SR_Ore_T03;Spread;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Scope_Athena_C_Ore_T03;AthenaJumpingFallingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Scope_Athena_UC_Ore_T03;AthenaJumpingFallingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Scope_Athena_R_Ore_T03;AthenaJumpingFallingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Scope_Athena_SR_Ore_T03;AthenaJumpingFallingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Scope_Athena_VR_Ore_T03;AthenaJumpingFallingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Hunter_Athena_C_Ore_T03;AthenaJumpingFallingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Hunter_Athena_UC_Ore_T03;AthenaJumpingFallingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Hunter_Athena_R_Ore_T03;AthenaJumpingFallingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Hunter_Athena_VR_Ore_T03;AthenaJumpingFallingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Hunter_Athena_SR_Ore_T03;AthenaJumpingFallingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Heavy_Athena_UR_Ore_T03;AthenaJumpingFallingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Heavy_Athena_SR_Ore_T03;AthenaJumpingFallingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Heavy_Athena_VR_Ore_T03;AthenaJumpingFallingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Heavy_Athena_R_Ore_T03;AthenaJumpingFallingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Scope_Suppressed_Athena_R_Ore_T03;AthenaJumpingFallingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Scope_Suppressed_Athena_VR_Ore_T03;AthenaJumpingFallingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Scope_Suppressed_Athena_SR_Ore_T03;AthenaJumpingFallingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Standard_Scope_Athena_SR_Ore_T03;AthenaJumpingFallingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Standard_Scope_Athena_VR_Ore_T03;AthenaJumpingFallingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Standard_Scope_Athena_HighTier_SR_Ore_T03;AthenaJumpingFallingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Standard_Scope_Athena_HighTier_VR_Ore_T03;AthenaJumpingFallingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Weather_Athena_SR_Ore_T03;AthenaJumpingFallingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Weather_Athena_VR_Ore_T03;AthenaJumpingFallingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;WaffleTruck_Sniper_DragonBreath;AthenaJumpingFallingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Weather_Athena_SR_Ore_T03;AthenaJumpingFallingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Heavy_Boom_Athena_SR_Ore_T03;AthenaJumpingFallingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Scope_Athena_C_Ore_T03;AthenaSprintingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Scope_Athena_UC_Ore_T03;AthenaSprintingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Scope_Athena_R_Ore_T03;AthenaSprintingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Scope_Athena_SR_Ore_T03;AthenaSprintingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Scope_Athena_VR_Ore_T03;AthenaSprintingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Hunter_Athena_C_Ore_T03;AthenaSprintingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Hunter_Athena_UC_Ore_T03;AthenaSprintingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Hunter_Athena_R_Ore_T03;AthenaSprintingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Hunter_Athena_VR_Ore_T03;AthenaSprintingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Hunter_Athena_SR_Ore_T03;AthenaSprintingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Heavy_Athena_UR_Ore_T03;AthenaSprintingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Heavy_Athena_SR_Ore_T03;AthenaSprintingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Heavy_Athena_VR_Ore_T03;AthenaSprintingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Heavy_Athena_R_Ore_T03;AthenaSprintingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Scope_Suppressed_Athena_R_Ore_T03;AthenaSprintingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Scope_Suppressed_Athena_VR_Ore_T03;AthenaSprintingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Scope_Suppressed_Athena_SR_Ore_T03;AthenaSprintingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Standard_Scope_Athena_SR_Ore_T03;AthenaSprintingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Standard_Scope_Athena_VR_Ore_T03;AthenaSprintingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Standard_Scope_Athena_HighTier_SR_Ore_T03;AthenaSprintingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Standard_Scope_Athena_HighTier_VR_Ore_T03;AthenaSprintingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Weather_Athena_SR_Ore_T03;AthenaSprintingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Weather_Athena_VR_Ore_T03;AthenaSprintingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;WaffleTruck_Sniper_DragonBreath;AthenaSprintingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Weather_Athena_SR_Ore_T03;AthenaSprintingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Heavy_Boom_Athena_SR_Ore_T03;AthenaSprintingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Scope_Athena_C_Ore_T03;StandingStillSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Scope_Athena_UC_Ore_T03;StandingStillSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Scope_Athena_R_Ore_T03;StandingStillSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Scope_Athena_SR_Ore_T03;StandingStillSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Scope_Athena_VR_Ore_T03;StandingStillSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Heavy_Athena_UR_Ore_T03;StandingStillSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Heavy_Athena_SR_Ore_T03;StandingStillSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Heavy_Athena_VR_Ore_T03;StandingStillSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Heavy_Athena_R_Ore_T03;StandingStillSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Scope_Suppressed_Athena_SR_Ore_T03;StandingStillSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Scope_Suppressed_Athena_VR_Ore_T03;StandingStillSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Scope_Suppressed_Athena_R_Ore_T03;StandingStillSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Standard_Scope_Athena_SR_Ore_T03;StandingStillSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Standard_Scope_Athena_VR_Ore_T03;StandingStillSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Standard_Scope_Athena_HighTier_SR_Ore_T03;StandingStillSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Standard_Scope_Athena_HighTier_VR_Ore_T03;StandingStillSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Weather_Athena_SR_Ore_T03;StandingStillSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Weather_Athena_VR_Ore_T03;StandingStillSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Hunter_Athena_C_Ore_T03;StandingStillSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Hunter_Athena_UC_Ore_T03;StandingStillSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Hunter_Athena_R_Ore_T03;StandingStillSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Hunter_Athena_VR_Ore_T03;StandingStillSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Hunter_Athena_SR_Ore_T03;StandingStillSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;WaffleTruck_Sniper_DragonBreath;StandingStillSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Weather_Athena_SR_Ore_T03;StandingStillSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Heavy_Boom_Athena_SR_Ore_T03;StandingStillSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Scope_Athena_C_Ore_T03;SpreadDownsights;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Scope_Athena_UC_Ore_T03;SpreadDownsights;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Scope_Athena_R_Ore_T03;SpreadDownsights;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Scope_Athena_SR_Ore_T03;SpreadDownsights;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Scope_Athena_VR_Ore_T03;SpreadDownsights;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Heavy_Athena_UR_Ore_T03;SpreadDownsights;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Heavy_Athena_SR_Ore_T03;SpreadDownsights;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Heavy_Athena_VR_Ore_T03;SpreadDownsights;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Heavy_Athena_R_Ore_T03;SpreadDownsights;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Scope_Suppressed_Athena_SR_Ore_T03;SpreadDownsights;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Scope_Suppressed_Athena_VR_Ore_T03;SpreadDownsights;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Scope_Suppressed_Athena_R_Ore_T03;SpreadDownsights;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Standard_Scope_Athena_SR_Ore_T03;SpreadDownsights;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Standard_Scope_Athena_VR_Ore_T03;SpreadDownsights;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Standard_Scope_Athena_HighTier_SR_Ore_T03;SpreadDownsights;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Standard_Scope_Athena_HighTier_VR_Ore_T03;SpreadDownsights;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Weather_Athena_SR_Ore_T03;SpreadDownsights;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Weather_Athena_VR_Ore_T03;SpreadDownsights;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Hunter_Athena_C_Ore_T03;SpreadDownsights;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Hunter_Athena_UC_Ore_T03;SpreadDownsights;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Hunter_Athena_R_Ore_T03;SpreadDownsights;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Hunter_Athena_VR_Ore_T03;SpreadDownsights;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Hunter_Athena_SR_Ore_T03;SpreadDownsights;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;WaffleTruck_Sniper_DragonBreath;SpreadDownsights;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Weather_Athena_SR_Ore_T03;SpreadDownsights;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Heavy_Boom_Athena_SR_Ore_T03;SpreadDownsights;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Scope_Athena_C_Ore_T03;MinSpeedForSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Scope_Athena_UC_Ore_T03;MinSpeedForSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Scope_Athena_R_Ore_T03;MinSpeedForSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Scope_Athena_SR_Ore_T03;MinSpeedForSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Scope_Athena_VR_Ore_T03;MinSpeedForSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Heavy_Athena_UR_Ore_T03;MinSpeedForSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Heavy_Athena_SR_Ore_T03;MinSpeedForSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Heavy_Athena_VR_Ore_T03;MinSpeedForSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Heavy_Athena_R_Ore_T03;MinSpeedForSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Scope_Suppressed_Athena_SR_Ore_T03;MinSpeedForSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Scope_Suppressed_Athena_VR_Ore_T03;MinSpeedForSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Scope_Suppressed_Athena_R_Ore_T03;MinSpeedForSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Standard_Scope_Athena_SR_Ore_T03;MinSpeedForSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Standard_Scope_Athena_VR_Ore_T03;MinSpeedForSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Standard_Scope_Athena_HighTier_SR_Ore_T03;MinSpeedForSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Standard_Scope_Athena_HighTier_VR_Ore_T03;MinSpeedForSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Weather_Athena_SR_Ore_T03;MinSpeedForSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Weather_Athena_VR_Ore_T03;MinSpeedForSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Hunter_Athena_C_Ore_T03;MinSpeedForSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Hunter_Athena_UC_Ore_T03;MinSpeedForSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Hunter_Athena_R_Ore_T03;MinSpeedForSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Hunter_Athena_VR_Ore_T03;MinSpeedForSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Hunter_Athena_SR_Ore_T03;MinSpeedForSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;WaffleTruck_Sniper_DragonBreath;MinSpeedForSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Weather_Athena_SR_Ore_T03;MinSpeedForSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Heavy_Boom_Athena_SR_Ore_T03;MinSpeedForSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Scope_Athena_C_Ore_T03;MaxSpeedForSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Scope_Athena_UC_Ore_T03;MaxSpeedForSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Scope_Athena_R_Ore_T03;MaxSpeedForSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Scope_Athena_SR_Ore_T03;MaxSpeedForSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Scope_Athena_VR_Ore_T03;MaxSpeedForSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Heavy_Athena_UR_Ore_T03;MaxSpeedForSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Heavy_Athena_SR_Ore_T03;MaxSpeedForSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Heavy_Athena_VR_Ore_T03;MaxSpeedForSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Heavy_Athena_R_Ore_T03;MaxSpeedForSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Scope_Suppressed_Athena_SR_Ore_T03;MaxSpeedForSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Scope_Suppressed_Athena_VR_Ore_T03;MaxSpeedForSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Scope_Suppressed_Athena_R_Ore_T03;MaxSpeedForSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Standard_Scope_Athena_SR_Ore_T03;MaxSpeedForSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Standard_Scope_Athena_VR_Ore_T03;MaxSpeedForSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Standard_Scope_Athena_HighTier_SR_Ore_T03;MaxSpeedForSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Standard_Scope_Athena_HighTier_VR_Ore_T03;MaxSpeedForSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Weather_Athena_SR_Ore_T03;MaxSpeedForSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Weather_Athena_VR_Ore_T03;MaxSpeedForSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Hunter_Athena_C_Ore_T03;MaxSpeedForSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Hunter_Athena_UC_Ore_T03;MaxSpeedForSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Hunter_Athena_R_Ore_T03;MaxSpeedForSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Hunter_Athena_VR_Ore_T03;MaxSpeedForSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Hunter_Athena_SR_Ore_T03;MaxSpeedForSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;WaffleTruck_Sniper_DragonBreath;MaxSpeedForSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Weather_Athena_SR_Ore_T03;MaxSpeedForSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Heavy_Boom_Athena_SR_Ore_T03;MaxSpeedForSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Scope_Athena_C_Ore_T03;AthenaCrouchingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Scope_Athena_UC_Ore_T03;AthenaCrouchingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Scope_Athena_R_Ore_T03;AthenaCrouchingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Scope_Athena_SR_Ore_T03;AthenaCrouchingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Scope_Athena_VR_Ore_T03;AthenaCrouchingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Heavy_Athena_UR_Ore_T03;AthenaCrouchingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Heavy_Athena_SR_Ore_T03;AthenaCrouchingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Heavy_Athena_VR_Ore_T03;AthenaCrouchingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Heavy_Athena_R_Ore_T03;AthenaCrouchingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Scope_Suppressed_Athena_SR_Ore_T03;AthenaCrouchingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Scope_Suppressed_Athena_VR_Ore_T03;AthenaCrouchingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Scope_Suppressed_Athena_R_Ore_T03;AthenaCrouchingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Standard_Scope_Athena_SR_Ore_T03;AthenaCrouchingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Standard_Scope_Athena_VR_Ore_T03;AthenaCrouchingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Standard_Scope_Athena_HighTier_SR_Ore_T03;AthenaCrouchingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Standard_Scope_Athena_HighTier_VR_Ore_T03;AthenaCrouchingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Weather_Athena_SR_Ore_T03;AthenaCrouchingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Weather_Athena_VR_Ore_T03;AthenaCrouchingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Hunter_Athena_C_Ore_T03;AthenaCrouchingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Hunter_Athena_UC_Ore_T03;AthenaCrouchingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Hunter_Athena_R_Ore_T03;AthenaCrouchingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Hunter_Athena_VR_Ore_T03;AthenaCrouchingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Hunter_Athena_SR_Ore_T03;AthenaCrouchingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;WaffleTruck_Sniper_DragonBreath;AthenaCrouchingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Weather_Athena_SR_Ore_T03;AthenaCrouchingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Heavy_Boom_Athena_SR_Ore_T03;AthenaCrouchingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Scope_Athena_C_Ore_T03;AthenaSlidingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Scope_Athena_UC_Ore_T03;AthenaSlidingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Scope_Athena_R_Ore_T03;AthenaSlidingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Scope_Athena_SR_Ore_T03;AthenaSlidingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Scope_Athena_VR_Ore_T03;AthenaSlidingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Heavy_Athena_UR_Ore_T03;AthenaSlidingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Heavy_Athena_SR_Ore_T03;AthenaSlidingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Heavy_Athena_VR_Ore_T03;AthenaSlidingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Heavy_Athena_R_Ore_T03;AthenaSlidingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Scope_Suppressed_Athena_SR_Ore_T03;AthenaSlidingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Scope_Suppressed_Athena_VR_Ore_T03;AthenaSlidingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Scope_Suppressed_Athena_R_Ore_T03;AthenaSlidingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Standard_Scope_Athena_SR_Ore_T03;AthenaSlidingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Standard_Scope_Athena_VR_Ore_T03;AthenaSlidingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Standard_Scope_Athena_HighTier_SR_Ore_T03;AthenaSlidingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Standard_Scope_Athena_HighTier_VR_Ore_T03;AthenaSlidingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Weather_Athena_SR_Ore_T03;AthenaSlidingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Weather_Athena_VR_Ore_T03;AthenaSlidingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Hunter_Athena_C_Ore_T03;AthenaSlidingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Hunter_Athena_UC_Ore_T03;AthenaSlidingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Hunter_Athena_R_Ore_T03;AthenaSlidingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Hunter_Athena_VR_Ore_T03;AthenaSlidingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_BoltAction_Hunter_Athena_SR_Ore_T03;AthenaSlidingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;WaffleTruck_Sniper_DragonBreath;AthenaSlidingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Weather_Athena_SR_Ore_T03;AthenaSlidingSpreadMultiplier;0
+DataTable=/Game/Athena/Items/Weapons/AthenaRangedWeapons;RowUpdate;Sniper_Heavy_Boom_Athena_SR_Ore_T03;AthenaSlidingSpreadMultiplier;0
`;

function extractDataTables(text) {
    return text.split("\n").filter(line => line.trim().startsWith("+DataTable="));
}

function bloomExists(content) {
    return content.includes("# Straight Bloom");
}

function addBloom() {
    fs.appendFileSync(defaultGamePath, bloomText, "utf8");
    console.log("\nBloom text added to DefaultGame.ini.\n");
}

function removeBloom(content) {
    const updatedContent = content.replace(bloomText, "\n");
    fs.writeFileSync(defaultGamePath, updatedContent.trim() + "\n", "utf8");
    console.log("\nBloom text removed from DefaultGame.ini.\n");
}

function handleStraightBloom() {
    let content = fs.readFileSync(defaultGamePath, "utf8");
    const hasBloom = bloomExists(content);

    if (hasBloom) {
        removeBloom(content);
    } else {
        addBloom();
    }

    const backend = require(path.join(__dirname, "backend.js"));
    backend.main();
}

handleStraightBloom();